version: "3"
services:
  # frontend:
  #   container_name: frontend
  #   restart: unless-stopped
  #   build:
  #     context: ./frontend
  #   command: ["yarn", "start"]
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend/:/frontend/
  #     - ./frontend/node_modules/:/frontend/node_modules
  #   environment:
  #     - CI=true
  #     - CHOKIDAR_USEPOLLING=true
  #     - REACT_APP_BACKEND_URL=http://localhost:8000
  #   tty: true

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - aiary

  backend:
    container_name: backend
    build:
      context: ./backend-spring
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - aiary

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server
    networks:
      - aiary

networks:
  aiary:
    driver: bridge